"""phase4_secure_sharing_and_revocation

Revision ID: 5a74e1173785
Revises: 568abfddfb48
Create Date: 2026-09-23 01:04:17.452075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a74e1173785'
down_revision: Union[str, Sequence[str], None] = '568abfddfb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identities',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_user_identities_key_id'), 'user_identities', ['key_id'], unique=False)
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('note_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.String(length=64), nullable=True),
    sa.Column('note_version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_note_id'), 'audit_events', ['note_id'], unique=False)
    op.create_table('key_envelopes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('note_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.String(length=64), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('wrapped_note_key', sa.Text(), nullable=False),
    sa.Column('ephemeral_public_key', sa.Text(), nullable=False),
    sa.Column('iv', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_envelopes_id'), 'key_envelopes', ['id'], unique=False)
    op.create_index(op.f('ix_key_envelopes_note_id'), 'key_envelopes', ['note_id'], unique=False)
    op.create_index(op.f('ix_key_envelopes_recipient_id'), 'key_envelopes', ['recipient_id'], unique=False)
    op.create_table('note_shares',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('note_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('key_envelope_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_shares_id'), 'note_shares', ['id'], unique=False)
    op.create_index(op.f('ix_note_shares_note_id'), 'note_shares', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_shares_owner_id'), 'note_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_note_shares_recipient_id'), 'note_shares', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_shares_recipient_id'), table_name='note_shares')
    op.drop_index(op.f('ix_note_shares_owner_id'), table_name='note_shares')
    op.drop_index(op.f('ix_note_shares_note_id'), table_name='note_shares')
    op.drop_index(op.f('ix_note_shares_id'), table_name='note_shares')
    op.drop_table('note_shares')
    op.drop_index(op.f('ix_key_envelopes_recipient_id'), table_name='key_envelopes')
    op.drop_index(op.f('ix_key_envelopes_note_id'), table_name='key_envelopes')
    op.drop_index(op.f('ix_key_envelopes_id'), table_name='key_envelopes')
    op.drop_table('key_envelopes')
    op.drop_index(op.f('ix_audit_events_note_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_key_id'), table_name='user_identities')
    op.drop_table('user_identities')
    # ### end Alembic commands ###
